=== tanishachauhan/XMLRepo/xml/xml_project/src/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT movies (movie+)>
<!ELEMENT movie (code,title,release-date?,theater-name+,city*)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT release-date(day,month,year)>
<!ELEMENT day(#PCDATA)>
<!ELEMENT month(#PCDATA)>
<!ELEMENT year(#PCDATA)>
<!ELEMENT threater-name (#PCDATA)>
<!ELEMENT city(#PCDATA)>

=== tanishachauhan/XMLRepo/xml/xml_project/src/mov.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "movies.dtd" >
<movies>
  <movie>
    <code>101</code>
    <title>perks of being a wallflower</title>
    <release-date>
    <day>13</day>
    <month>6</month>
    <year>2019</year>>
    </release-date>
    <theater-name>INOX</theater-name>
    <threater-name>CityPride</threater-name>
    <city>Pune</city>
    <city>Mumbai</city>
    <city>Delhi</city>
    <city>Indore</city>
      </movie>
      <movie>
      <code>105</code>
      <title>Reborn</title>
      <release-date>
      <day>12</day>
      <month>7</month>
      </release-date>
      </movie>
      
</movies>
